server:
    port: 7788
    tomcat:
        threads:
            min-spare: 20

spring:
    profiles:
        active: local
    application:
        name: mqtt-springboot
    main:
        allow-bean-definition-overriding: true
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false

management:
    endpoints:
        web:
            base-path: /
            exposure:
                include: info,health,scheduledtasks,prometheus
            path-mapping:
                prometheus: metrics
    metrics:
        # 参考文档：https://cloud.tencent.com/document/product/1416/56031
        # 下面选项建议打开，以监控 http 请求的 P99/P95 等，具体的时间分布可以根据实际情况设置
        distribution:
            sla:
                http:
                    server:
                        # requests: 1ms,5ms,10ms,50ms,100ms,200ms,500ms,1s,5s
                        requests: 10ms,50ms,100ms,200ms,500ms,1s,5s
        # 在 Prometheus 中添加特别的 Labels
        tags:
            # 必须加上对应的应用名，因为需要以应用的维度来查看对应的监控
            application: ${spring.application.name}
    endpoint:
        health:
            show-details: always
    info:
        git:
            mode: full